# Минимальная конфигурация для приватного инстанса.
# Для продакшена потребуется limiter/redis и генерация secret_key.
use_default_settings: true

server:
  secret_key: "dev-only-change-me"
  limiter: false
  public_instance: false

ui:
  static_use_hash: true

search:
  safe_search: 1
  autocomplete: ""

