openrouter:
  models:
    - openai/gpt-5.2
    - google/gemini-3-flash-preview
    - google/gemini-3-pro-preview
    - x-ai/grok-4.1-fast
    - z-ai/glm-4.7
    - deepseek/deepseek-v3.2-speciale
    - deepseek/deepseek-v3.2
    - anthropic/claude-haiku-4.5
    - anthropic/claude-sonnet-4.5